# Generated by Django 4.1.6 on 2023-02-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='please enter the film name', max_length=256)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('video', models.FileField(upload_to='videos/')),
                ('rating', models.FloatField(default=0)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('about', models.TextField(blank=True, null=True)),
                ('films', models.ManyToManyField(related_name='actors', to='app_film.filmmodel')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
    ]
